// Copyright 2026 The MathWorks, Inc.

package auth

import (
	"crypto/sha256"
	"encoding/hex"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/mathworks/matlab-proxy-go/internal/config"
)

func newTestAuth(t *testing.T, enabled bool, token string, port int) *TokenAuth {
	t.Helper()
	cfg := &config.Config{
		EnableTokenAuth: enabled,
		AuthToken:       token,
		Port:            port,
	}
	ta, err := New(cfg)
	if err != nil {
		t.Fatalf("New() error: %v", err)
	}
	return ta
}

func TestNew_Disabled(t *testing.T) {
	ta := newTestAuth(t, false, "", 8080)
	if ta.Enabled() {
		t.Error("expected Enabled() = false")
	}
	if ta.Token() != "" {
		t.Error("expected empty token when disabled")
	}
}

func TestNew_AutoGeneratedToken(t *testing.T) {
	ta := newTestAuth(t, true, "", 8080)
	if !ta.Enabled() {
		t.Error("expected Enabled() = true")
	}
	if ta.Token() == "" {
		t.Error("expected auto-generated token")
	}
	if len(ta.Token()) != 64 { // 32 bytes hex-encoded
		t.Errorf("expected 64-char token, got %d", len(ta.Token()))
	}
}

func TestNew_CustomToken(t *testing.T) {
	ta := newTestAuth(t, true, "my-secret", 8080)
	if ta.Token() != "my-secret" {
		t.Errorf("expected token 'my-secret', got %q", ta.Token())
	}
}

func TestTokenHash(t *testing.T) {
	ta := newTestAuth(t, true, "test-token", 8080)
	h := sha256.Sum256([]byte("test-token"))
	expected := hex.EncodeToString(h[:])
	if ta.TokenHash() != expected {
		t.Errorf("expected hash %q, got %q", expected, ta.TokenHash())
	}
}

func TestCookieName_PortScoped(t *testing.T) {
	ta1 := newTestAuth(t, true, "tok", 8080)
	ta2 := newTestAuth(t, true, "tok", 9090)
	if ta1.cookieName == ta2.cookieName {
		t.Errorf("cookie names should differ for different ports, both got %q", ta1.cookieName)
	}
	if ta1.cookieName != "mwi-auth-session-8080" {
		t.Errorf("expected 'mwi-auth-session-8080', got %q", ta1.cookieName)
	}
}

func TestValidateRequest_Disabled(t *testing.T) {
	ta := newTestAuth(t, false, "", 8080)
	req := httptest.NewRequest("GET", "/", nil)
	if !ta.ValidateRequest(req) {
		t.Error("disabled auth should always validate")
	}
}

func TestValidateRequest_QueryParam(t *testing.T) {
	ta := newTestAuth(t, true, "secret123", 8080)

	req := httptest.NewRequest("GET", "/?mwi-auth-token=secret123", nil)
	if !ta.ValidateRequest(req) {
		t.Error("valid query param should pass")
	}

	req = httptest.NewRequest("GET", "/?mwi-auth-token=wrong", nil)
	if ta.ValidateRequest(req) {
		t.Error("invalid query param should fail")
	}
}

func TestValidateRequest_Header(t *testing.T) {
	ta := newTestAuth(t, true, "secret123", 8080)

	req := httptest.NewRequest("GET", "/", nil)
	req.Header.Set("mwi-auth-token", "secret123")
	if !ta.ValidateRequest(req) {
		t.Error("valid header should pass")
	}

	req = httptest.NewRequest("GET", "/", nil)
	req.Header.Set("mwi-auth-token", "wrong")
	if ta.ValidateRequest(req) {
		t.Error("invalid header should fail")
	}
}

func TestValidateRequest_HashAccepted(t *testing.T) {
	ta := newTestAuth(t, true, "secret123", 8080)

	req := httptest.NewRequest("GET", "/", nil)
	req.Header.Set("mwi-auth-token", ta.TokenHash())
	if !ta.ValidateRequest(req) {
		t.Error("token hash should be accepted")
	}
}

func TestValidateRequest_Cookie(t *testing.T) {
	ta := newTestAuth(t, true, "secret123", 8080)

	req := httptest.NewRequest("GET", "/", nil)
	req.AddCookie(&http.Cookie{Name: ta.cookieName, Value: ta.TokenHash()})
	if !ta.ValidateRequest(req) {
		t.Error("valid session cookie should pass")
	}

	req = httptest.NewRequest("GET", "/", nil)
	req.AddCookie(&http.Cookie{Name: ta.cookieName, Value: "stale-value"})
	if ta.ValidateRequest(req) {
		t.Error("stale cookie should fail")
	}
}

func TestValidateRequest_NoCredentials(t *testing.T) {
	ta := newTestAuth(t, true, "secret123", 8080)
	req := httptest.NewRequest("GET", "/", nil)
	if ta.ValidateRequest(req) {
		t.Error("request with no credentials should fail")
	}
}

func TestAccessURL(t *testing.T) {
	ta := newTestAuth(t, true, "tok123", 8080)
	url := ta.AccessURL("http://localhost:8080")
	expected := "http://localhost:8080?mwi-auth-token=tok123"
	if url != expected {
		t.Errorf("expected %q, got %q", expected, url)
	}
}

func TestAccessURL_WithExistingQuery(t *testing.T) {
	ta := newTestAuth(t, true, "tok123", 8080)
	url := ta.AccessURL("http://localhost:8080?foo=bar")
	expected := "http://localhost:8080?foo=bar&mwi-auth-token=tok123"
	if url != expected {
		t.Errorf("expected %q, got %q", expected, url)
	}
}

func TestAccessURL_Disabled(t *testing.T) {
	ta := newTestAuth(t, false, "", 8080)
	url := ta.AccessURL("http://localhost:8080")
	if url != "http://localhost:8080" {
		t.Errorf("disabled auth should return URL unchanged, got %q", url)
	}
}

func TestSetSessionCookie(t *testing.T) {
	ta := newTestAuth(t, true, "secret123", 8080)
	w := httptest.NewRecorder()
	ta.SetSessionCookie(w)

	cookies := w.Result().Cookies()
	if len(cookies) != 1 {
		t.Fatalf("expected 1 cookie, got %d", len(cookies))
	}
	c := cookies[0]
	if c.Name != "mwi-auth-session-8080" {
		t.Errorf("expected cookie name 'mwi-auth-session-8080', got %q", c.Name)
	}
	if c.Value != ta.TokenHash() {
		t.Errorf("expected cookie value %q, got %q", ta.TokenHash(), c.Value)
	}
	if !c.HttpOnly {
		t.Error("cookie should be HttpOnly")
	}
}

func TestSetSessionCookie_Disabled(t *testing.T) {
	ta := newTestAuth(t, false, "", 8080)
	w := httptest.NewRecorder()
	ta.SetSessionCookie(w)
	if len(w.Result().Cookies()) != 0 {
		t.Error("disabled auth should not set cookie")
	}
}

func TestMiddleware_Allowed(t *testing.T) {
	ta := newTestAuth(t, true, "secret123", 8080)
	handler := ta.Middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))

	req := httptest.NewRequest("GET", "/?mwi-auth-token=secret123", nil)
	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", w.Code)
	}
}

func TestMiddleware_Forbidden(t *testing.T) {
	ta := newTestAuth(t, true, "secret123", 8080)
	handler := ta.Middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))

	req := httptest.NewRequest("GET", "/", nil)
	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	if w.Code != http.StatusForbidden {
		t.Errorf("expected 403, got %d", w.Code)
	}
}

func TestClearStaleCookieMiddleware(t *testing.T) {
	ta := newTestAuth(t, true, "new-token", 8080)
	handler := ta.ClearStaleCookieMiddleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))

	// Request with a stale cookie (from a previous session)
	req := httptest.NewRequest("GET", "/", nil)
	req.AddCookie(&http.Cookie{Name: "mwi-auth-session-8080", Value: "old-session-hash"})
	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	// Should expire the stale cookie
	cookies := w.Result().Cookies()
	found := false
	for _, c := range cookies {
		if c.Name == "mwi-auth-session-8080" {
			found = true
			if c.MaxAge != -1 {
				t.Errorf("expected MaxAge=-1 to expire cookie, got %d", c.MaxAge)
			}
		}
	}
	if !found {
		t.Error("expected stale cookie to be expired")
	}
}

func TestClearStaleCookieMiddleware_ValidCookie(t *testing.T) {
	ta := newTestAuth(t, true, "current-token", 8080)
	handler := ta.ClearStaleCookieMiddleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))

	// Request with a valid cookie
	req := httptest.NewRequest("GET", "/", nil)
	req.AddCookie(&http.Cookie{Name: "mwi-auth-session-8080", Value: ta.TokenHash()})
	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	// Should NOT expire a valid cookie
	for _, c := range w.Result().Cookies() {
		if c.Name == "mwi-auth-session-8080" && c.MaxAge == -1 {
			t.Error("valid cookie should not be expired")
		}
	}
}
